Add README
apertium/pairviewer pull request #7
Opened 2018-12-08 17:07 UTC by amuritna

2018-12-08 21:13 UTC, sushain97 requested changes

2018-12-08 21:13 UTC, sushain97 commented on README.md
> +- filter by language pair progress branch, directionality, stem count, creation date, and date of last update
```suggestion
- filter by language pair progress state, directionality, stem count, creation date, and date of last update
```

2018-12-08 21:13 UTC, sushain97 commented on README.md
> +The relevant Apertium wiki page (along with local setup instructions!) is available [**here**](http://wiki.apertium.org/wiki/Pair_viewer).
Links with the text here are not ideal. Instead just say something like "See the relevant Apertium wiki page for local setup instructions" with the wiki page part linked.

2018-12-09 01:42 UTC, amuritna commented
@sushain97 I've changed all those now.

2018-12-09 02:39 UTC, sushain97 approved these changes

2018-12-09 02:39 UTC, merged